### ISSUE TITLE
"CryptoObject" support 

### ISSUE THREAD

**Issue by sergeykomlach** [sergeykomlach/AdvancedBiometricPromptCompat#11]
Currently no way to pass CryptoObject to library

**Comment by Salat-Cx65** [comment]
TBD.
Branch ["WIP-cryptoobject" ](https://github.com/Salat-Cx65/AdvancedBiometricPromptCompat/tree/WIP-cryptoobject) created, but research around pitfalls and limitations - required

**Comment by sergeykomlach** [comment]
https://fi5t.xyz/posts/biometric-underauthentication/
