### ISSUE TITLE
Check compatibility with new Windows Subsystem for Android and Windows Hello

### ISSUE THREAD

**Issue by sergeykomlach** [sergeykomlach/AdvancedBiometricPromptCompat#172]

**Comment by Salat-Cx65** [comment]
Maybe useful https://github.com/cansik/librealsense-java

**Comment by sergeykomlach** [comment]
16.02.2022 - the same device (Acer_Aspire7), still biometric doesn't work

**Comment by sergeykomlach** [comment]
09.05.2022 - the same device (Acer_Aspire7), still biometric doesn't work.

Ticket closed for now
