### ISSUE TITLE
android:attr/lStar not found

### ISSUE THREAD

**Issue by knifemaster7** [sergeykomlach/AdvancedBiometricPromptCompat#265]
I'm using dev.skomlach:biometric:2.0.90, minSDKVersion 21, target SDK 29, compile SDK 29, and kotlin version 1.5.
I'm getting error `AAPT: error: resource android:attr/lStar not found.`

**Comment by sergeykomlach** [comment]
@knifemaster7 according to this answer https://stackoverflow.com/a/69042271 - the easiest way to solve this problem - is just to upgrade the targetSDK/compileSDK to 31 or higher.
I hope it's acceptable for your project.

**Comment by sergeykomlach** [comment]
Closed due inactivity
