### ISSUE TITLE
Bug: face authentication dialog out of screen bounds in portrait layout for tablet device

### ISSUE THREAD

**Issue by sandboiii** [sergeykomlach/AdvancedBiometricPromptCompat#275]
Device: samsung galaxy tab s7
Android version: 12
When using face authentication dialog in portrait layout for tablet device it goes out of screen bounds (i.e. too wide).   
  
Specifications:
  
<img src="https://user-images.githubusercontent.com/17468894/168039626-98e6079b-fe87-472c-b711-a5fa3803fb19.jpg" width="300">  
  
  
  
Face authentication dialog in landscape layout:  
  
<img src="https://user-images.githubusercontent.com/17468894/168039827-1515405a-0f63-449d-9718-7493f789d2dd.jpg" width="300">  
    
  
   
Face authentication dialog in portrait layout:  
  
<img src="https://user-images.githubusercontent.com/17468894/168040004-49a4425b-8759-4761-865f-c7987805c33c.jpg" width="300">

**Comment by sandboiii** [comment]
Maybe the problem with
```
<dimen name="dialog_width">830dp</dimen>
```
In [biometric/src/main/res/values-sw600dp-v31/dimens.xml](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/blob/main/biometric/src/main/res/values-sw600dp-v31/dimens.xml#L21)

**Comment by sergeykomlach** [comment]
Hi.
```dialog_width``` is the right point, as a hotfix it's fine.
but I would like to find some more "general" way to set dialog width for tablets to avoid tons of ```value-bla-bla```

**Comment by sandboiii** [comment]
One thing that I don't understand is why there is bigger `dialog_width` specifically for v31? How sdk version affects screen size?

**Comment by sergeykomlach** [comment]
It was the wrong decision to use `dialog_width` from the begging :(.
In general "own" (non-system) dialogs were developed with the mind that they should look and behave similarly to system UI (exception: OEM solutions like Samsung)
On different SDK versions, minor difference exists, like padding, corners, etc., including dialog width.
On some SDK versions, the dialog is wider, on some - not.
Now I see that  `dialog_width`  makes more problems than solves, so I focused on layouts refactoring to avoid `dialog_width` usage at all.

**Comment by sandboiii** [comment]
Can you please make a build with the quick fix?

**Comment by sergeykomlach** [comment]
2.0.99 published
