### ISSUE TITLE
One Plus 9 fingerprint unlock (Not fixed)

### ISSUE THREAD

**Issue by jamiehiggins** [sergeykomlach/AdvancedBiometricPromptCompat#309]
Unfortunately #305 does not appear to be fixed when I'm importing the new version of the library.

I've dived into the code to try and work out why it was working on your APK build and the difference is as follows:

I believe you sent me a debug build and because of this the isExperimentalFeaturesEnabled flag was set to true.

This results in the following code being executed (in BiometricPrompApi28Impl):

```
            if (builder.isExperimentalFeaturesEnabled() && builder.getPrimaryAvailableTypes().size == 1 && builder.getPrimaryAvailableTypes()
                    .toMutableList()[0] == BiometricType.BIOMETRIC_FINGERPRINT
            ) {
                forceToFingerprint = true
            }
```

and the forceToFingerprint is set to true.

I am able to get it working by setting the experimental features to true when I'm calling.

**Comment by sergeykomlach** [comment]
@jamiehiggins can we close the issue?

**Comment by jamiehiggins** [comment]
@sergeykomlach Yep all seems good now. Thanks again for the quick fix.
