### ISSUE TITLE
LEGACY_API BIOMETRIC_FACE Prompt not closing correctly

### ISSUE THREAD

**Issue by MakTszHim** [sergeykomlach/AdvancedBiometricPromptCompat#316]
On the Test app after closing the LEGACY_API/BIOMETRIC_FACE Prompt by tapping the upper empty space outside the prompt box, the prompt will keep on the screen forever. A strange empty prompt will show up by changing orientation or back from background.

**Comment by him1231** [comment]
> On the Test app after closing the LEGACY_API/BIOMETRIC_FACE Prompt by tapping the upper empty space outside the prompt box, the prompt will keep on the screen forever. A strange empty prompt will show up by changing orientation or back from background.


https://user-images.githubusercontent.com/35519340/195534723-2fef9085-ac30-4aa9-a006-9e2b557055ba.mp4

**Comment by sergeykomlach** [comment]
Can be related [#276](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/issues/276)

**Comment by MakTszHim** [comment]
@sergeykomlach tested on nova 9 SE, prompt closed correctly on rotation and no longer show up when come from background.
