### ISSUE TITLE
i went show popup biometric dialog

### ISSUE THREAD

**Issue by sarayut8** [sergeykomlach/AdvancedBiometricPromptCompat#328]
val biometricPromptCompat = BiometricPromptCompat.Builder(BiometricAuthRequest(BiometricApi.AUTO, BiometricType.BIOMETRIC_ANY, BiometricConfirmation.ALL), this)
                .setTitle("Biometric demo")
                .setSubtitle("Test by gus")
                .setDescription("Biometric Description: BlaBlablabla Some very long text BlaBlablabla and more text and more and more and more")
                .setNegativeButton("Cancel", null)
                .build()

//not show popup biometric dialog

**Comment by sergeykomlach** [comment]
Please check the test app
https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/blob/main/app/src/main/java/dev/skomlach/biometric/app/utils/BiometricExtension.kt
OR minimal code example
https://github.com/sergeykomlach/AdvancedBiometricPromptCompat#minimal-code-example

In short:
```val biometricPromptCompat = BiometricPromptCompat.Builder(BiometricAuthRequest(BiometricApi.AUTO, BiometricType.BIOMETRIC_ANY, BiometricConfirmation.ALL), this)
.setTitle("Biometric demo")
.setSubtitle("Test by gus")
.setDescription("Biometric Description: BlaBlablabla Some very long text BlaBlablabla and more text and more and more and more")
.setNegativeButton("Cancel", null)
.build()

 biometricPromptCompat.authenticate(object : BiometricPromptCompat.AuthenticationCallback() {
        override fun onSucceeded(confirmed: Set<AuthenticationResult>) {
          

        }

        
        override fun onFailed(reason: AuthenticationFailureReason?, msg: CharSequence?) {
           
        }
    })
