### ISSUE TITLE
Make ping locations customizable

### ISSUE THREAD

**Issue by jamiehiggins** [sergeykomlach/AdvancedBiometricPromptCompat#357]
I have just had a user who was inspecting network traffic from my app and was freaking out that my app was contacting aliexpress.com. I couldn't understand how this was even possible but after poking around in my code base I found that it was this library that is using this domain for a connectivity check  (along with 1.1.1.1 and google.com).

Could you please make the domains used for this ping functionaltiy configurable by the user as it's very hard to explain why my app is contacting aliexpress and it certainly looks very dodgy from a users perspective.

**Comment by sergeykomlach** [comment]
`PingConfig` added, so you will be able to configure the host's list (rev 2.0.61)
Also aliexpress.com was removed.
But please note: In some regions, Cloudflare (1.1.1.1) or/and google.com can be blocked by a national firewall (like in China). As a solution - maybe some national (aliexpress.com, yandex.ru etc.) and/or other global hosts can be used.

**Comment by jamiehiggins** [comment]
That's great. Thanks so much for supporting this.
