### ISSUE TITLE
class file has wrong version 61.0, should be 55.0

### ISSUE THREAD

**Issue by vantien1401** [sergeykomlach/AdvancedBiometricPromptCompat#358]
Hi Team, I have a issue relate Runtime version: 11.0.15+0-b2043.56-8887301 aarch64
an/app/build/tmp/kapt3/stubs/stagT6Debug/com/m3/kz/util/biometric/BiometricLibHelper.java:8: error: cannot access BiometricAuthRequest
    private dev.skomlach.biometric.compat.BiometricAuthRequest authRequest;
                                         ^
  bad class file: gradle/caches/transforms-3/d1411fb266574b6004871d87bb095b25/transformed/jetified-biometric-2.1.80-api.jar(/dev/skomlach/biometric/compat/BiometricAuthRequest.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
an/app/build/tmp/kapt3/stubs/stagT6Debug/com/m3/kz/util/biometric/BiometricLibHelper.java:11: error: cannot access AuthenticationResult
    private kotlin.jvm.functions.Function1<? super java.util.Set<dev.skomlach.biometric.compat.AuthenticationResult>, kotlin.Unit> successCallback;
                                                                                              ^
  bad class file: .gradle/caches/transforms-3/d1411fb266574b6004871d87bb095b25/transformed/jetified-biometric-2.1.80-api.jar(/dev/skomlach/biometric/compat/AuthenticationResult.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
an/app/build/tmp/kapt3/stubs/stagT6Debug/com/m3/kz/util/biometric/BiometricLibHelper.java:12: error: cannot access AuthenticationFailureReason
    private kotlin.jvm.functions.Function1<? super dev.skomlach.biometric.compat.AuthenticationFailureReason, kotlin.Unit> failedCallback;
                                                                                ^
  bad class file:gradle/caches/transforms-3/d1411fb266574b6004871d87bb095b25/transformed/jetified-biometric-2.1.80-api.jar(/dev/skomlach/biometric/compat/AuthenticationFailureReason.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
`

**Comment by vantien1401** [comment]
> Android Studio Electric Eel | 2022.1.1 Patch 2
Build #AI-221.6008.13.2211.9619390, built on February 17, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    wu.seal.tool.jsontokotlin (3.7.4)
    com.suusan2go.kotlin-fill-class (1.0.19.1)

**Comment by sergeykomlach** [comment]
Hi, 
Yep, looks like the problem was with JavaVersion - library compiled with JavaVersion.VERSION_17, but you need JavaVersion.VERSION_11

I downgrade JavaVersion and publish the new version `2.0.81`

**Comment by sergeykomlach** [comment]
Tested with [JavaVersion.VERSION_1_8 ](https://github.com/ezatpanah/BiometricAuthentication-Youtube/tree/main) - all good.
Problem solved
