### ISSUE TITLE
S8+ - Using fingerprint while in Iris recognition

### ISSUE THREAD

**Issue by RobbWatershed** [sergeykomlach/AdvancedBiometricPromptCompat#365]
Hi,

One of my testers with a S8+ device is reporting the following issue : "[the device] does prompt for iris recognition as, but it doesn't respond to the fingerprint sensor at all (usually even if I'm being prompted for iris unlock I can use the fingerprint sensor instead)"

As I'm unable to test that on my own hardware, I'm submitting an issue here. Is there a way to enable multiple responses to one given prompt as my user describes ?

Thanks in advance,
-Robb

**Comment by sergeykomlach** [comment]
Hi.
Well, with Samsung devices we have an interesting story.
If I remember correctly, starting from the Galaxy S8 or S9 and/or Note series from the same years, Samsung introduced its own UI system (see screenshot, something like pre-BiometricPrompt from AOSP).
This new UI system allows you to choose what type of biometric can be used - fingerprint, iris, or face (dependent on the device, of course) if multiple enrolled.  However the chosen biometric works as an "exclusive" one, so if you choose the face, the fingerprint will not work at the same time. 
Additionally, (on some devices) the user is able to set one biometric as "active/primary".
So, dealing with biometrics on Samsung is hell :(

But anyway, we can try to deal somehow with this, I just need a bit of time and more details from you.
![4IxVy](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/assets/1887383/d34002bb-5353-4a4a-9cd4-daf60519dfe7)

**Comment by RobbWatershed** [comment]
Thank you for looking into this. What kind of details do you need?

**Comment by sergeykomlach** [comment]
Closed due to inactivity
