### ISSUE TITLE
S8+ / Iris recognition - Camera as alignment guide

### ISSUE THREAD

**Issue by RobbWatershed** [sergeykomlach/AdvancedBiometricPromptCompat#366]
Hi,

The same tester using an S8+ is reporting another issue (albeit less important than #365) : "Usually iris unlock shows me the camera view to help align my eyes, but [the app] isn't showing the camera and just giving text prompts to help adjust"

Is there a way for AdvancedBiometricPromptCompat to enable the camera guidance he's talking about, or is it too specific to Samsung ?

Thanks in advance for your help,
-Robb

**Comment by sergeykomlach** [comment]
@RobbWatershed 
Hi.
Can you try the APK https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/raw/face_iris_ui/app/app-debug.apk ?
I don't have a Samsung S8 for testing, but some UI for Face alignment was added a few years ago, just for limited usage, that now expanded for all API's that support View/Surface for preview

**Comment by RobbWatershed** [comment]
Okay, so my tester got a little confused by all the buttons of that app. Could you give a quick guidance about what to test ? 😅 

He told me he tried "AUTO/BIOMETRIC_IRIS" button, which caused his phone to lock up and restart <.<

**Comment by sergeykomlach** [comment]
@RobbWatershed most probably that's a side-effect of the changes that I made for the camera preview - the library passes the `Surface ` reference where (I expect) the system will draw the camera preview. Maybe something with `Surface ` something wrong (size/hwAcceleration/etc) - it's a new area for me, so hard to say for sure.


What to test:
- First, let's get some screenshots/photos with the screen where the camera preview is missed.
It sounds like ABCP custom dialog on the screen, but for Samsung - should be the system one displayed. Would be nice to clarify what we have on the screen
- Can you confirm that `AUTO/BIOMETRIC_IRIS` leads to a permanent device reboot?
- Except  `AUTO/BIOMETRIC_IRIS` , is any other buttons with `BIOMETRIC_IRIS` ? How do they behave? 

Tnx

**Comment by sergeykomlach** [comment]
Hi @RobbWatershed 
I'm keep looking for solution with camera preview.
Can you check the recent build https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/raw/face_iris_ui/app/app-debug.apk
It also include possible fix for [#365](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/issues/365)
Thank you in advance

**Comment by RobbWatershed** [comment]
Thanks for the reminder. I've sent an update to the tester who reported that issue.

**Comment by RobbWatershed** [comment]
I don't have any feedback from my user, plus no other user has reported any similar issue => Closed
