### ISSUE TITLE
min sdkCompileSdk 34 problem

### ISSUE THREAD

**Issue by laixindev** [sergeykomlach/AdvancedBiometricPromptCompat#375]
![Snipaste_2023-12-05_17-21-01](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/assets/10086446/839b2f76-1e3d-4ad7-90c8-ff5fb120f7e7)
when I use [AdvancedBiometricPromptCompat] in my project  ( sdk 33)  it throw a error...

how to fix it?

And my project is already have meizu_fingerprint.jar.  which have duplicate with Flyme_fingerprint.jar in this project....
Any solution about this ? thx

**Comment by sergeykomlach** [comment]
- The ticket looks like wrongly named, the minSDK for this library is 16 (Aka Jelly Bean)
- Please check the current targetSDK/compileSDK version of your project, it seems like it lower than 34 (recommended version by Google)
- Please, provide a properly oriented screenshot of the error - hard to read and understand what the problem
- If you already use Flyme_fingerprint.jar, you can remove your JAR file OR exclude Meizu package from this library via "exclude" option in Gradle
Tnx
