### ISSUE TITLE
metadata is 1.8.0 , expected version is 1.5.1 problem

### ISSUE THREAD

**Issue by laixindev** [sergeykomlach/AdvancedBiometricPromptCompat#376]
hello, I wonder if this project can lower the kotlin version to 1.5.1?  It seems like 1.8.0 which confict with my project

**Comment by sergeykomlach** [comment]
Hi.
Well, Kotlin 1.5.1 is already 2,5 years old (https://github.com/JetBrains/kotlin/releases/tag/v1.5.10).
It will be hard to revert the library to such an old Kotlin/Gradle version and keep compatibility with modern AOSP versions/dependencies/AGP.
Did you think about the project upgrade to some recent AGP/Kotlin/dependencies versions?
